
-- =================================================================
-- FIX IMPORT ERROR (428C9)
-- Description: Mengubah kolom ID dari 'GENERATED ALWAYS' menjadi 'GENERATED BY DEFAULT'
-- agar Supabase mengizinkan import ID manual dari file CSV/Backup.
-- =================================================================

-- 1. Perbaiki Tabel Users (Agar bisa import users_rows.csv)
ALTER TABLE public.users 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 2. Perbaiki Tabel Registrations (Agar bisa import registrations.csv)
ALTER TABLE public.registrations 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 3. Perbaiki Tabel Attendance Sessions (Agar bisa import sesi lama)
ALTER TABLE public.attendance_sessions 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 4. Perbaiki Tabel News (Berita)
ALTER TABLE public.news 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 5. Perbaiki Tabel Gallery
ALTER TABLE public.gallery 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 6. Perbaiki Tabel Sliders
ALTER TABLE public.sliders 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 7. Perbaiki Tabel Media Posts
ALTER TABLE public.media_posts 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- 8. Perbaiki Tabel Korwils
ALTER TABLE public.korwils 
ALTER COLUMN id SET GENERATED BY DEFAULT;

-- =================================================================
-- PENTING: SETELAH IMPORT SELESAI
-- Setelah Anda berhasil import CSV, sangat disarankan menjalankan perintah 
-- sinkronisasi sequence (penomoran) agar data baru tidak error (duplicate key).
-- 
-- Jalankan perintah ini SETELAH semua CSV berhasil di-upload:
-- SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id),0) + 1, false) FROM users;
-- =================================================================
